cmd_array[0] : /Library/Frameworks/Python.framework/Versions/3.10/bin
cmd_array[1] : /opt/homebrew/bin
cmd_array[2] : /opt/homebrew/sbin
cmd_array[3] : /usr/local/bin
cmd_array[4] : /usr/bin
cmd_array[5] : /bin
cmd_array[6] : /usr/sbin
cmd_array[7] : /sbin
cmd_array[8] : /Library/Apple/usr/bin
cmd_array[9] : /Users/acho/.cargo/bin
cmd_array[10] : /Users/acho/Library/Python/3.8/bin
